name: flutter_profile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.0.0
  flutter_vector_icons: ^1.0.0
  cupertino_icons: ^1.0.4
  responsive_framework: ^0.1.5

  get_it: ^7.2.0
  injectable: ^1.5.3

  flutter_bloc: ^8.0.1

  dartz: ^0.10.0-nullsafety.2
  rxdart: ^0.27.3
  path_provider: ^2.0.8
  internet_connection_checker: ^0.0.1+3

  shared_preferences: ^2.0.12
  http: ^0.13.4
  equatable: ^2.0.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  injectable_generator: ^1.5.3
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/img/profile.png

  fonts:
    - family: AquinoDemo
      fonts:
        - asset: assets/fonts/AquinoDemo.ttf

    - family: Nisebuschgardens
      fonts:
        - asset: assets/fonts/Nisebuschgardens.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoBold.ttf
